# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Todd Hoff on Github 
email: toddhoffious@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sorry, I don't have an awesome description of my new site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://toddhoff.github.io" # the base hostname & protocol for your site
twitter_username: toddhoffious
github_username:  ToddHoff

# Build settings
markdown: kramdown
